server:
   port: ${PORT:8082}
   session:
      timeout: 28800
spring:
   profiles:
      active: ${PROFILE_ACTIVE:local}
   data:
      web:
         pageable:
            default-page-size: 5
            max-page-size: 500
            one-indexed-parameters: true
   servlet:
      multipart:
         max-file-size: 25MB
         max-request-size: 25MB